//[PROMPT START]:Write code to load a png image
use image::DynamicImage;
use image::io::Reader as ImageReader;
use std::env;

fn main() {
    let current_dir = env::current_dir().expect("Failed to get current directory");
    let image_path = current_dir.join("images/awesomeface.png").to_str().unwrap().to_string();
    println!("Hello, amazing world!");
    //1.Load Image
    let image = load_image(&image_path);
    //2.Convert to fixed data type
    //3. Manipulate image
    //4. Save image
    //5. Mark down all prompts and code generated by an AI
}

fn load_image(path: &str) -> DynamicImage {
    let reader = ImageReader::open(path).expect("Failed to open image file");
    reader.decode().expect("Failed to decode image")
}
//[PROMPT END]:Write code to load a png image
