fn main() {
    println!("Hello, amazing world!");
    //1.Load Image
    //2.Convert to fixed data type
    //3. Manipulate image
    //4. Save image
    //5. Mark down all prompts and code generated by an AI
}
